### ISSUE TITLE
add in some background info about FW

### ISSUE THREAD

**Issue by flynnduism** [fermyon/finicky-whiskers#33]
Now that we've published blog posts about Finicky Whiskers, it would be great to tie them together so that folks who play the game can learn more. 

I'd like to add in a subtle prompt like:

> What _is_ Finicky Whiskers? See what happens beneath the surface of 'The World's Most Adorable Manual Load Generator'

and link it to https://www.fermyon.com/blog/finicky-whiskers-part-1-intro

**Comment by technosophos** [comment]
Absolutely!!!

**Comment by mikkelhegn** [comment]
The current version has the footer overlaying the buttons:

<img width="1523" alt="image" src="https://user-images.githubusercontent.com/12242001/173814607-53ca8544-c958-43dd-be3e-699486f5c15f.png">

I think it's caused by this: https://github.com/fermyon/finicky-whiskers/pull/36

**Comment by vdice** [comment]
What do we want to do for this one?  Shall I deploy the earlier version to prod -- or are we looking at a fix prior to next week's conference?

**Comment by flynnduism** [comment]
Yeah it's on my list, need to fix it as soon as possible. Perhaps moving the banner to the top (above the progress bar) to avoid overlaps

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
