### ISSUE TITLE
Upgrade to latest Spin SDK

### ISSUE THREAD

**Issue by jpflueger** [fermyon/finicky-whiskers#61]
As we continue to showcase this application at conferences as a demo, it would be nice to update Finicky Whiskers to use the latest Spin SDK as it is currently it is on Spin v0.4. Would be great to get this in for Wasm I/O in case people we talk to go to look at the code but priority on this seems low. Adding this issue to track the work, I'll probably take a stab at it on a Friday.

**Comment by adamreese** [comment]
SDK's have now been updated to v1.4.1
